integ/test_integ.py
src/conn_handler.c

Seems that correct value for rate in timers is average amount of measurements per second.
Otherwise, please, explain the purpose of dividing sum of all timings by length of flush interval. I can't think of any use for this statistic.
In extended counters, it makes sense, but not in timers.

Fix timers rate output

---

sinks/cloudwatch.sh

This sink puts custom metrics on cloudwatch. The metric key needs to follow a
special pattern so that the sink can extract the necessary attributes. The format is
described in the sink itself.
I tested the sink manually with the following command:
```
echo "RabbitMQ/TEST:MessagesReady:fu=bax|1|`date "+%s"` 
RabbitMQ/TEST:MessagesUnacked:fu=bay|2|`date "+%s"` 
RabbitMQ/TEST:MessagesTotal:fu=baz|3|`date "+%s"`
" | sinks/cloudwatch.sh
```
and will further test it on a real server with statsite running. Since it is written in bash
and is using the aws cli I fear it will never be fast and never be suitable for high load.

Add a cloudwatch sink.

---

src/statsite.c

The previous behavior was to log to stderr iff stdout was a TTY.
However, this made it cumbersome to log in environments where syslog is
not available (Docker) or stdout/stderr logging is conventional
(Supervisord), since it may not always be trivial to arrange for a
pseudo-tty to be allocated for no purpose other than persuading statsite
to log to stderr.
In cases where statsite is daemonizing, logging to stderr has little
value since daemonization closes stderr. When statsite is not
daemonizing, it's likely that stderr logging is desirable, and when not,
trivially disabled by redirecting stderr to /dev/null.

Log to stderr when not daemonizing

---

src/networking.c

Hi,
Congratulations for the tool! I noticed two memory leaks on `addrinfo` struct. I think this patch fixes them.

Fix memory leaks on getaddrinfo

---

README.md

per issue #120 the binary protocol doesn't support flags. I've updated the docs to indicate this.

Binary protocol doesn't support flags

---

Makefile

otherwise make will only look at test_runner mtime and not rebuild if
dependent sources have changed

Makefile: let scons handle test_runner

---

integ/test_binary.py
integ/test_binary_stream.py
integ/test_extended_counters.py
integ/test_integ.py
integ/test_stdin.py

noticed statsite left running upon `make integ` and files left in `/tmp`, fix by not using a shell and exec statsite instead

Integ cleanup

---

integ/test_integ.py
src/conn_handler.c

namely to support scientific notation, see also #123

conn_handler: fallback to strtod if needed

---

Makefile
rpm/statsite.conf.example
rpm/statsite.initscript
rpm/statsite.service
rpm/statsite.spec

Some operational changes:
- Fixes several issues which made building RPMs impossible
- Adds a statsite user on RPM creation
- Run everything as this user
- Adds a systemd control file
There are a serious of other changes in this repo, so this is a cherry-pick of some mainline changes - if there is interest in general development plans let me know.

Modernize RPM and init for systemd

---

sinks/graphite.py

The docstring for the flush method says
`metrics` : A list of (key,value,timestamp) tuples
while the code expects each metric to be a string with format key|value|timestamp

Fix docstring in graphite.py

---

src/conn_handler.c
src/metrics.c
src/metrics.h
src/timer.c
src/timer.h
tests/runner.c
tests/test_metrics.c
tests/test_streaming.c
tests/test_timer.c

fixes #142 
Simple example test using netcat: Executed these in succession
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1
Output from custom sink script:
Before:
'timers.foo.count|4|1439367451’,
'timers.foo.mean|5.000000|1439367451',
'timers.foo.sample_rate|0.400000|1439367451’,
After:
'timers.foo.count|8|1439365840’,
'timers.foo.mean|5.000000|1439365840’,
'timers.foo.sample_rate|0.800000|1439365840’,

Fix timer count

---

README.md
integ/test_extended_counters_include.py
src/config.c
src/config.h
src/conn_handler.c
src/statsite.c
tests/runner.c
tests/test_config.c

Hey,
Would you like to add the ability to specify which extended counters to include? If yes does it need any changes?
I made it backwards compatible so if the new config is not set all extended counters will be included. All tests still pass.
fyi, we are running statsite to send close 1 million metrics per second to graphite we have 16 statsite daemons running in 16 servers. With the original Node.js statsd implementation + proxies each server used to have 6 cores at 100% usage. With statsite I'm getting 1 core at less than 20% usage for the same amount of metrics.
Thanks,
Gihad

Extended counters include

---

rpm/statsite.initscript

This function isn't defined anywhere and makes the `restart` command fail.

remove broken call to configtest from statsite init script

---

sinks/graphite.py

We noticed some problems with the graphite sink producing uncaught exceptions if the graphite backend is not available. This bugfixes solved these problems for us.
We use the graphite sink with attemps=1 (no retry).

Small bugfixes

---

README.md
integ/test_timers_include.py
src/config.c
src/config.h
src/conn_handler.c
tests/runner.c
tests/test_config.c

Inspired by #145, I've created a PR to add a `timers_include` config option to allow you to specify which timer metrics to emit.
As with the `extended_counters_include` option it's backwards compatible. You can additionally specify a whether to emit `median` and `sample_rate`

Timers include

---

rpm/statsite.conf.example

Not sure if this is an issue on my system, but statsite is having trouble finding the relative path.

use absolute path in example

---

rpm/statsite.service
rpm/statsite.spec
rpm/statsite.tmpfiles.conf

Hi. I'd appreciate someone going over this (I'm not an rpm packaging expert). Fixes for statsite user creation and systemd pid dir persistence using /etc/tmpfiles.d/....tested on CentOS7

CentOS7 systemd related fixes

---

integ/test_integ.py
src/conn_handler.c

This pull request fixes two issues:
1. + sign could not be used with `c` type metrics
2. If a metric has an error while parsing, the rest of the buffer was not consumed. Until another event have been received.

Fix +sign used on counters and parsing error 

---

deps/murmurhash/MurmurHash3.c
src/conn_handler.c
src/heap.c

I tested this on OS X and Alpine. But not on Windows.

Fixes compilation when using musl libc as well as other compiler warnings.

---

README.md

Hello.
I think that package `libtool` must be mentioned as requirement. This package is not installed as dependency of another required packages on Ubuntu. For example, I have installed packages:
```
root@cs29839:~/statsite# dpkg -l build-essential autoconf automake
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                               Version                Architecture           Description
+++-==================================-======================-======================-==========================================================================
ii  autoconf                           2.69-9                 all                    automatic …
```

Add libtool as requirement in Install instruction.

---

.gitignore
Makefile.am
rpm/statsite.spec

I know very little for automake but I was having issue with RPMBUILDROOT being empty. It ends up doing failing on mkdir -v  (empty value).
Maybe you're setting that value by command line but I guess we should have default?

Fix RPMBUILDROOT

---

README.md

This was a little confusing as I had disable global_prefix in statsite directly. Also others sink don't seem to add a prefix (Correct me if I'm wrong)
FYI there is an easy workaround I simply added an empty string in the stream_cmd
stream_cmd = python sinks/graphite.py localhost 2003 ''
To maintain compatibility I adjusted README stream_cmd as this could cause a little bit of confusion on users that didn't realize that is happening.

Graphite sinks add "statsite" prefix by default

---

sinks/graphite.py
sinks/influxdb.py
sinks/librato.py

Using a bare `except:` in python will catch and swallow unintentional exceptions, like `SystemExit` or `KeyboardInterrupt` that will prevent the process from exiting normally. Typically when someone does `except:`, what they really mean is "catch any normal exceptions", which means to use `Exception`.
For reference, the `Exception` hierarchy can be found here: https://docs.python.org/2/library/exceptions.html#exception-hierarchy

Don't use a bare except

---

configure.ac
rpm/statsite.spec

* latest tag is `v0.8.0`
* the code is still set to `0.7.1`. So RPM built from `master` or
tag `v0.8.0` will still have version set to `0.7.1`

Update hardcoded version to match latest tag

---

src/streaming.c

On an embedded linux system using Busybox (https://busybox.net/),
/bin/sh (and other simple linux programs) are really just
symlinks to Busybox. Busybox then infers which program it should
run from argv[0]. This commit changes the argv[0] passed to
/bin/sh to be "sh" as opposed to "streaming" which allows Busybox
to properly infer that it needs to launch a shell.

src/streaming.c: Add busybox support

---

src/conn_handler.c

If multiple input lines are received, not resetting the sample_rate to 1.0 will result in incorrect .count values.

reset sample_rate on each iteration

---

rpm/statsite.spec

Fix incorrect path to the generated statsite binary file.

BUGFIX: Fix rpm build error

---

bootstrap.sh
configure.ac

* buildconfig.h.in does not get generated without 'autoheader' in
bootstrap.sh
* add the missing '#' to 'Checks for header files' which is meant
to be a comment. Otherwise, 'configure' will complain about
'Checks: command not found'

Fix a couple of build issues

---

README.md
src/config.c
src/config.h
src/networking.c

This adds a configuration option to the Statsite config file called
`udp_rcvbuf` which is used to make a setsockopt() call on the UDP
listen socket to set the SO_RCVBUF option.
Busy UDP sockets can benefit from having a larger than normal socket buffer
compared to the rmem_default setting.  This allows one to instruct
Statsite to set a different size buffer for the UDP socket.  Presumably,
rmem_max.

Add udp_rcvbuf configuration option to support larger socket buffers

---

sinks/graphite.py

- removed prefix special handling as it is always defined (might need bool handling but it should be done on class init)
- ensure no spaces and slashes in metric name, replace with underscore

Graphite sink whitespaces

---

sinks/graphite.py

The PR #236 introduces a bug that inverts the order of timestamps and values in graphite plain-text protocol.

[Patch] fix order of value/timestamp for graphite

---

debian/conf/statsite.conf
debian/control
debian/rules
debian/statsite.dirs
debian/statsite.install
debian/statsite.links
debian/statsite.postinst
debian/statsite.prerm
debian/statsite.service
debian/statsite.upstart

Updated debianization, tested with Trusty/Xenial
check-0.10.0 doesn't come with Trusty, I use Xenial-backported in-house build.
changes file wasn't updated as I don't rely on it (it's updated during my build process)

statsite debianization

---

sinks/graphite.py

A handful of refactors to clean up the graphite sink and also not change the default behavior of not modifying key names which changed in #236 without, IMHO, adequate notice.
Sanitization of key name now follows behavior from txstatsd which squashes spaces into underbars, slashed into hyphens and all other non-alphanumeric gets dropped.
Also reduction of code in global scope and corrected overly broad exception handling.

Improved graphite sink

---

src/config.c
src/config.h
src/networking.c

this should address #206 and #215, the new timer logic is enabled via a new configuration variable. defaulting to disabled, in which case there are no  changes to the timer behavior.
feedback and/or comments much appreciated

align flush interval to clock

---

src/ascii_parser.make

this might help with autotools intgegration, running
`make -f ascii_parser.make [ std | condensed ]`
should build the appropriate parser

add condensed and std targets for parser

---

sinks/graphite.py

If Graphite server is not reachable do not block on connect.
I set a default timeout of 2 seconds for awaiting connection (it can be set by command line argument) after that the connection fails. If a value `infinity` is passed from command line the socket timeout is not set.
When the graphite host is pingable but the tcp connection hangs, the python process remains alive and a new one is spawn every flush interval. In this situation also the `init.d` script fails to stop the service and leaves all the python processes alive.

graphyte.py: add socket timeout option

---

rpm/statsite.spec

This fixes the error seen from a "make rpms" on RHEL7:
.....
statsite-0.8.1/config.status
statsite-0.8.1/Makefile
statsite-0.8.1/libtool
statsite-0.8.1/statsite-0.8.1.tar.gz
rm -r /tmp/statsite-0.8.1
rm: remove write-protected regular file ‘/tmp/statsite-0.8.1/.git/objects/pack/p                                                                                             ack-52fd7cab4ea93c41fd5b2d87811467fe547402f5.pack’? y
rm: remove write-protected regular file ‘/tmp/statsite-0.8.1/.git/objects/pack/p                                                                                             ack-52fd7cab4ea93c41fd5b2d87811467fe547402f5.idx’? y
mkdir -vp /tmp/rpm-build
cp -v *.tar.gz /tmp/rpm-build
‘statsite-0.8.1.tar.gz’ -> ‘/tmp/rpm-build/statsite-0.8.1.tar.gz’
cp -v rpm/statsite.spec …

Bump version inside spec file to build RPM

---

src/config.c

this change addresses #265 , the string of skipped characters can be modified to support additional whitespace characters that should be skipped.

allow whitespace in extended counters csv parser

---

.travis.yml
README.md
integ/test_http.py
sinks/http.py

Implements an interface that allows metrics to be sent via HTTP in the following JSON format:
```
{
"metrics": [
{"key": "foo", "value": "123", "timestamp": "1500000000"},
{"key": "bar", "value": "456", "timestamp": "1500000001"},
]
}
```

implement http sink

---

Makefile.am
rpm/statsite.spec

Force removal of /tmp/statsite directory without interaction.
Adding missing file to specfile to get rid of rpmbuild errors

spec and Makefile updates

---

Dockerfile

This PR adds a basic Dockerfile. This is a two-stage build, where the first stage being only for binary production. The second stage pulls the build binary and the sinks over from the first stage.
The user needs to mount their config file, though they can change the path where it lives by overriding the `STATSITE_CONFIG_PATH` env var.
I've kept the paths the same as what you'd get from doing a `make install` for consistency's sake.
The end result is that users a have an included and convenient way to build and/or deploy statsite in a containerized environment.

Add a basic Dockerfile

---

Dockerfile
statsite.docker.example

There is 2 commits in this PR:
ece69e9 - The sinks weren't COPY correctly
b6207b4 - Added a example config file so that you can  have a worker container with a simple :
`docker run statsite/statsite:0.8.1-6`
And change CMD and ENTRYPOINT so you can override it easily
`docker run -v /mount/statsite:/tmp statsite/statsite:0.8.1-6 -f /tmp/statsite.conf`
I had issue using the ENV variable because it was incorrectly passed from the shell to the statsite

Add sink to dockerfile

---

Dockerfile

This is required by the OpenTSDB sink.  It increases the image size from 157MB to 201MB in case that's a problem.

Add nodejs to Dockerfile.

---

integ/test_integ.py
src/ascii_parser.c
src/ascii_parser_condensed.rl
src/ascii_parser_std.rl

The code to use the `sample_rate` in timer metrics was already in place, I have just enabled it in the grammar and added a test.

Add sample rate for timer metrics

---

rpm/statsite.spec

- BuildRequires to include autoconf, libtool utils
- Run ./autogen, %configure in %build stage.

rpm/statsite.spec: update BuildRequires, %build steps.

---

INSTALL.md

the latest pytest version is 4.4.0 And it has changed a lot. If I install the pytest 4.4.0, the test code will fail. So I add the version info on the INSTALL.md.

add pytest and requests version

---

debian/control

When building in a clean environment (eg sbuild chroot), test suite
fails, if these packages are not installed.

Update debian dependencies for stretch

---

src/hashmap.c
src/hashmap.h

**bug description**
#define DEFAULT_CAPACITY 128
int hashmap_init(int initial_size, hashmap **map) comment says that default value is 64, yet sets the initial size to DEFAULT_CAPACITY should function parameter be less or equal to 0.
**fix description**
Fixed comment, assuming define value takes precedence.

Fix for inconsistency accross #define and comment of hashmap_init
