statsite/statsite

Makefile

run scons --clean during make clean

---

README.md

Probably should have included this with #114. Also, I see Travis failed for that PR....hope it wasn't my change :worried:

Update documentation to reflect logging behavior

---

rpm/statsite.initscript
rpm/statsite.spec

Update specfile to restart on upgrade.
Update specfile to ignore monit if not present.
Update initscript to work around stale pid file.

Some RPM love.

---

sinks/opentsdb.js

A node.js/iojs sink for opentsdb.

OpenTSDB Sink

---

README.md
integ/test_binary_stream.py
src/conn_handler.c

also a small fix to Makefile to DTRT when changing source and running `make test` right after

Update binary stream type

---

src/counter.c
src/counter.h
src/metrics.c
tests/runner.c
tests/test_counter.c

As discussed, fixes count for COUNTER type. 
Related to:
https://github.com/armon/statsite/pull/144

Fix counter count

---

sinks/influxdb.py

Log appropriate message depends on response code.

Update sink influxdb v.0.9

---

SConstruct
sinks/gmetric.py
sinks/statsite_json_sink.rb
src/statsite.c

Various changes required to build statsite on SunOS derived OSes. Also removes shebangs from scripts as pkgsrc disapproves

Build for SunOS

---

sinks/librato.py

This adds support for parsing extended_counters, which should address #139. Extended counters are parsed the same way as timer metrics are, meaning they generate a complex gauge in Librato.
After surveying our own metric names at Librato I found that there wasn't an easy to disambiguate between normal counters and extended_counters in the line protocol. We have quite a few counter metric names that end in `.count`, so I couldn't parse these as extended counters given the same prefix of `counts.`. Therefore, if the user has enabled extended_counters in statsite they must also set `extended_counters=true` in the Librato sink config.

Add support for extended_counters.

---

README.md

Update README to reflect autotools change in https://github.com/armon/statsite/pull/184

Update README - autotools change

---

sinks/graphite.py

Been fiddling with this project lately and I've found it to be great for my needs. Kudos for the idea of doing this in C!
This PR will support a new parameter for the graphite (carbon) sink, "pickle", that will support the pickle protocol for sinking data into graphite (carbon). Current sink only supports the regular "lines" protocol. 
More information about the protocols in:
http://graphite.readthedocs.io/en/latest/feeding-carbon.html
I tried to keep backwards compatibility so default protocol is "lines". I basically added a new function `flush_pickle` and on initialisation I choose which "flush" function will be used, the one that formats lines and the ones that formats pickles.

support for pickle protocol on graphite sink

---

src/cm_quantile.c

Small PR to resolve #223 - unused counter variable in cm_quantile.c

Remove unused variable

---

src/conn_handler.c
src/networking.c

The initial problem here is that in high UDP traffic situations the
event loop would spend multiple seconds, even 30 or 45+, reading UDP
data in handle_udp_message().  As the event loop didn't make iterations
this would push out when timer events ran.  This would cause gaps in
Graphite data immediately followed by an artificial spike where summary
metrics were generated for a window much longer than the configured
flush interval.
This tunes up handle_udp_message() to make use of the 64 KiB circular
buffer.  The function reads until the buffer is full (assuming max
packet size is 1500 bytes) or the read would block.  I've removed any
memory allocation from the loop as well.  This is level triggered so
the next poll cycle will continue processing UDP data if ready.  This
insures that we …

Fix timer drift under high UDP traffic conditions

---

src/conn_handler.c
src/streaming.c

I think that 256KB is enough to so simple thread

reduce stack size of handler thread to 256KB instead default 8MB

---

sinks/graphite.py

* whitespace cleanup
* long lines rewrapped
* log formatting changed to use implicit arg passing:
https://docs.python.org/2/library/logging.html#logging.Logger.debug

style: Improve PEP8 compliance of graphite sink

---

README.md

document aligned_flush config option

---

INSTALL.md

update docs after adding requests as a test dependency in #267

add requests as a python test dependency

---

sinks/graphite.py

There is an issue with the graphite sink when sending a lot of different metrics, which hit us while testing statsite in production. The problem is that all the metrics are sent in one go, and the pickle protocol have a limit of 1MB per pickle:
https://github.com/graphite-project/carbon/blob/master/lib/carbon/protocols.py#L212
The proposed patch splits the metrics on batches with a maximum size and send a pickle per batch. This is not a perfect solution, and could not be enough if the metric names are very long, but we have quite long metric names and the current max size works fine for us (we have this running on live with decent traffic).
This also affect the lines protocol, but is working fine and this seems like a better way to send the metrics in any case, because python doesn't need …

Fix graphite sink to flush the metrics on batches

---

README.md

Added a little section over docker after https://github.com/statsite/statsite/pull/282

Added Documentation over the docker usage

---

integ/test_librato.py
sinks/librato.py

Librato updates to support metric tagging

---

rpm/statsite.spec

Amend SPEC file to use standard %{_macros} for file paths and commands.

Use standard RPM macros
